jobs:
  include:
    - language: rust
      rust:
        - stable
        - beta
      before_script:
        - rustup component add clippy
      script:
        - cd cli && cargo clippy -- -D warnings
    - language: python
      python:
        - 3.8
      install:
        - pip install -r requirements.txt
      script:
        - cd scrapper && pylint