version: "3.9"
services:
  redis:
    image: redis:6.2.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./private/data/redis:/data
    command: redis-cli --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
  cli:
    build:
      context: cli
    volumes:
      - ./cli/:/usr/src/cli
  scrapper:
    build:
      context: scrapper