version: "3.9"
services:
  redis:
    image: redis:6.2.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./private/data/redis:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
  server:
    build:
      context: ./
    environment:
      GIN_MODE: development
    ports:
      - "8080:8080"
    depends_on:
      redis:
       condition: service_healthy